#!/usr/bin/bash

lib_path="$HOME/.memos"

delete_lines () {
    del_lines=""
    del="d;"
    for number in $@ 
    do
        del_lines="$del_lines$number$del"
    done
    sed -i "${del_lines}" $lib_path
}

execute_lines () {
    for number in $@
    do    
        command=$(sed "${number}q;d;" $lib_path)
        echo "$command"
        $command
    done    
}

case "$1" in
    -[Ss]|--[Ss][Hh][Oo][Ww])
        echo "These are your memos right now:"
        cat -n $lib_path
        ;;
    -[Aa]|--[Aa][Dd][Dd])
        if [ "$2" ]
        then
            echo "$2" >> $lib_path 
        else
            cat -n $lib_path
            echo "Type in the memo you would like to add."
            read memo
            echo $memo >> $lib_path
        fi
        ;;
    -[Rr]|--[Rr][Uu][Nn])
        if [ $2 ]
        then
            execute_lines "${@:2}"    
        else
            cat -n $lib_path
            echo "Type the line numbers that you would like to run (they wil run in order)"
            read run_lines
            IFS=' ' read -r -a run_numbers <<< "$run_lines"
            execute_lines "${run_numbers[@]}"
        fi
    ;;
    -[Dd]|--[Dd][Ee][Ll][Ee][Tt][Ee])
        if [ $2 ]
        then
            delete_lines "${@:2}"
        else
            cat -n $lib_path
            echo "Type the line number of the memo you like to delete."
            read delete_numbers
            IFS=' ' read -r -a del_numbers <<< "$delete_numbers"
            delete_lines "${del_numbers[@]}"
        fi
        ;;
    -[Uu]|--[Uu][Nn][Ii][Nn][Ss][Tt][Aa][Ll][Ll])
        echo "type yes or y to uninstall"
        read uninstall
        if [ $uninstall == "yes" ] || [ $uninstall == "y" ]
        then
            sudo rm -r $lib_path
            sudo rm -r /bin/memo
            echo "Memo is deleted"
        else
            echo "Stopt the uninstall"
        fi
        ;;
    -[Hh]|--[Hh][Ee][Ll][Pp])
        echo "These are the arguments that you can use."
        echo '-a, --add         adds the text you type after it to your memos file. use "" if you would like to add a sentence.'
        echo "-s, --show        shows all your memos in your memo file."
        echo "-d, --delete      deletes the line by number in memos file. you can add multiple lines to delete at once or type all and delete all the lines."
        echo "-r, --run         runs it like a command. selected by number of line in memos file."
        echo "-u, --uninstall   deletes the program and your memos."
        echo "-h, --help        runs this command."
        ;;
    *)
        echo "These are your memos right now:"
        cat -n $lib_path
        ;;
esac
